# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
df = pd.read_csv("student_alcohol.csv")

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [3]:
df = df.loc[:, "school":"guardian"]

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [4]:
capitalize = lambda x: x.capitalize() if isinstance(x, str) else x

### Step 6. Capitalize both Mjob and Fjob

In [5]:
df["Mjob"] = df["Mjob"].apply(capitalize)
df["Fjob"] = df["Fjob"].apply(capitalize)

### Step 7. Print the last elements of the data set.

In [6]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [7]:
#Data gốc ko đổi vì đang thao tác trên df chứ ko phải file gốc 

df = pd.read_csv("student_alcohol.csv")

df["Mjob"] = df["Mjob"].apply(capitalize)
df["Fjob"] = df["Fjob"].apply(capitalize)

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [8]:
def majority(age):
    return age > 17

df["legal_drinker"] = df["age"].apply(majority)

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [9]:
df[df.select_dtypes(include="number").columns] *= 10